# Handle PWR button to shutdown/reboot -- useful in Qemu (virt-manager)
# Depends on syslogd having started. Redirect any output to log.
service acpid {
	description = "ACPI daemon"
	runlevel    = "2345"
	command     = "acpid -f"
}
