# Consoles to start Finit built-in getty on when system is up
tty tty1 {
	runlevel = "12345"
	device   = "/dev/tty1"
	noclear  = true
	nowait   = true
}
tty tty2 {
	runlevel = "2345"
	device   = "/dev/tty2"
	noclear  = true
	nowait   = true
}
tty tty3 {
	runlevel = "2345"
	device   = "/dev/tty3"
	noclear  = true
	nowait   = true
}
