# Silly Busybox ntpd has no option to use syslog when running in foreground
service ntpd {
	description = "NTP daemon"
	runlevel    = "2345"
	conditions  = { "pid/syslogd" }
	log { }
	command     = "ntpd -n -N -p pool.ntp.org"
}
