# Start syslogd as soon as possible, should always run
# Start klogd as soon as possible, but after syslogd
service syslogd {
	description = "Syslog daemon"
	runlevel    = "S12345"
	command     = "syslogd -n"
}
service klogd {
	description = "Kernel log daemon"
	runlevel    = "S12345"
	conditions  = { "pid/syslogd" }
	command     = "klogd -n"
}
