# Start SSH daemon as soon as basic networking comes up
service dropbear {
	description = "Dropbear SSH daemon"
	runlevel    = "2345"
	envfile     = "-/etc/conf.d/dropbear"
	command     = "dropbear -R -F $DROPBEAR_OPTS"
}
