# Busybox ntpd has no option to use syslog when running in foreground
service ntpd {
	description = "NTP daemon"
	runlevel    = "2345"
	conditions  = { "pid/syslogd" }
	envfile     = "-/etc/conf.d/ntpd"
	log { }
	command     = "ntpd -n $NTPD_OPTS"
}
