# Start syslogd as soon as possible, should always run
# Start klogd as soon as possible, but after syslogd
service syslogd {
	description = "Syslog daemon"
	runlevel    = "S12345"
	envfile     = "-/etc/conf.d/syslog"
	command     = "syslogd -n $SYSLOGD_OPTS"
}
service klogd {
	description = "Kernel log daemon"
	runlevel    = "S12345"
	conditions  = { "pid/syslogd" }
	envfile     = "-/etc/conf.d/klogd"
	command     = "klogd -n $KLOGD_OPTS"
}
