# Handle PWR button to shutdown/reboot -- useful in Qemu (virt-manager)
# Depends on a syslog daemon having started. Redirect any output to log.
service acpid {
	description = "ACPI daemon"
	runlevel    = "2345"
	conditions  = { "pid/syslogd" }
	envfile     = "-/etc/default/acpid"
	log { }
	command     = "acpid -f $OPTIONS"
}
