task anacron {
	description = "Anacron jobs"
	runlevel    = "2345"
	conditions  = { "sys/pwr/ac", "pid/syslogd" }
	envfile     = "-/etc/default/anacron"
	stop-signal = "usr1"
	command     = "anacron -d -q $ANACRON_ARGS"
}
