# To ignore errors like "org.freedesktop.hostname1", update the env file with
# "--noplugin=hostname", i.e. append to BLUETOOTHD_OPTS
service bluetoothd {
	description = "Bluetooth service"
	runlevel    = "2345"
	envfile     = "-/etc/default/bluetooth"
	log { file = "/dev/null" }
	command     = "/usr/libexec/bluetooth/bluetoothd -n $BLUETOOTHD_OPTS"
}
