service cron {
	description = "Background job processing daemon"
	runlevel    = "2345"
	conditions  = { "sys/pwr/ac", "pid/syslogd" }
	envfile     = "-/etc/default/cron"
	command     = "cron -f $EXTRA_OPTS"
}
