# On some systems, bootstrap can be really quick and cause elogind
# to not start before a user has managed to log in.  To prevent
# this, add <pid/elogind> as condition to your TTYs in getty.conf
service elogind {
	description = "Login manager"
	runlevel    = "2345"
	conditions  = { "pid/syslogd" }
	command     = "/usr/libexec/elogind"
}
