# Start rsyslogd as soon as possible, should always run
# Provides pid/syslogd condition
service syslogd {
	description = "Reliable syslog daemon"
	runlevel    = "S12345"
	envfile     = "-/etc/default/rsyslog"
	command     = "rsyslogd -n $RSYSLOGD_OPTIONS"
}
