# Simple NTP client (SNTP)
service sntpd {
	description = "SNTP client"
	runlevel    = "2345"
	conditions  = { "net/route/default" }
	envfile     = "-/etc/default/sntpd"
	command     = "sntpd -n $SNTPD_OPTIONS"
}
