# Start SSH daemon as soon as basic networking comes up
service sshd {
	description = "OpenSSH daemon"
	runlevel    = "2345"
	conditions  = { "net/lo/up" }
	envfile     = "-/etc/default/ssh"
	command     = "/usr/sbin/sshd -D $SSHD_OPTS"
}
