# Test service, only used for `make check`, not for public use
service testserv {
	description = "Test serv daemon"
	runlevel    = "S123456789"
	conditions  = { "boot/testserv" }
	notify      = "none"
	pidfile     = "/run/testserv.pid"
	cgroup system {}
	command     = "/sbin/serv -n -p -i testserv"
}
